# Generated by Django 5.2.8 on 2026-04-07 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_order_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='address',
        ),
    ]
