# Generated by Django 5.2.8 on 2026-03-06 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_role'),
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.subcategory'),
        ),
    ]
