# Generated by Django 5.2.8 on 2026-03-11 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0004_discount_end_date_discount_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='image_url',
        ),
        migrations.AddField(
            model_name='productimage',
            name='image',
            field=models.ImageField(default=2, upload_to='products/'),
            preserve_default=False,
        ),
    ]
