# Generated by Django 5.2.8 on 2026-03-16 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0008_product_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorylog',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='seller.productvariant'),
        ),
    ]
